INSERT INTO coupe_du_monde VALUES ('1', '1998-06-10', '1998-07-12');
INSERT INTO coupe_du_monde VALUES ('2', '2002-05-31', '2002-06-30');
INSERT INTO coupe_du_monde VALUES ('3', '2006-06-09', '2006-07-9');
INSERT INTO coupe_du_monde VALUES ('4', '2010-06-11', '2010-07-11');
INSERT INTO coupe_du_monde VALUES ('5', '2014-06-12', '2014-07-13');
INSERT INTO coupe_du_monde VALUES ('6', '2018-06-14', '2018-07-15');

INSERT INTO pays_coupe VALUES ('Uruguay', '1');
INSERT INTO pays_coupe VALUES ('Italie', '2');
INSERT INTO pays_coupe VALUES ('France', '3');
INSERT INTO pays_coupe VALUES ('Canada', '4');
INSERT INTO pays_coupe VALUES ('Bresil', '5');
INSERT INTO pays_coupe VALUES ('Suisse', '6');

INSERT INTO stade VALUES ('Rocket Center', 'Hillford', '38000', 'Uruguay', '1709');
INSERT INTO stade VALUES ('Bob Center', 'Harmsby', '32000', 'Italie', '1883');
INSERT INTO stade VALUES ('Super Field', 'Croma', '36000', 'France', '1810');
INSERT INTO stade VALUES ('Fern field', 'Bobski', '44000', 'Canada', '1514');
INSERT INTO stade VALUES ('Grandios Stadium', 'Hadderfoo', '30000', 'Bresil', '1879');
INSERT INTO stade VALUES ('Cookie Center', 'Sier', '44000', 'Suisse', '1651');

INSERT INTO pays_enum VALUES ('Uruguay');
INSERT INTO pays_enum VALUES ('Italie');
INSERT INTO pays_enum VALUES ('France');
INSERT INTO pays_enum VALUES ('Canada');
INSERT INTO pays_enum VALUES ('Bresil');
INSERT INTO pays_enum VALUES ('Suisse');
INSERT INTO pays_enum VALUES ('Suede');
INSERT INTO pays_enum VALUES ('Chili');
INSERT INTO pays_enum VALUES ('Angleterre');
INSERT INTO pays_enum VALUES ('Mexique');
INSERT INTO pays_enum VALUES ('Allemagne');
INSERT INTO pays_enum VALUES ('Portugal');
INSERT INTO pays_enum VALUES ('Autriche');
INSERT INTO pays_enum VALUES ('Yougoslavie');
INSERT INTO pays_enum VALUES ('Union sovietique');
INSERT INTO pays_enum VALUES ('Tchecoslovaquie');
INSERT INTO pays_enum VALUES ('Pologne');
INSERT INTO pays_enum VALUES ('Argentine');
INSERT INTO pays_enum VALUES ('Belgique');
INSERT INTO pays_enum VALUES ('Croatie');
INSERT INTO pays_enum VALUES ('Pays-Bas');
INSERT INTO pays_enum VALUES ('Coree du Sud');
INSERT INTO pays_enum VALUES ('Japon');
INSERT INTO pays_enum VALUES ('Russie');
INSERT INTO pays_enum VALUES ('Maroque');
INSERT INTO pays_enum VALUES ('Egypt');
INSERT INTO pays_enum VALUES ('Grece');
INSERT INTO pays_enum VALUES ('Qatar');
INSERT INTO pays_enum VALUES ('Etats-Unis');
INSERT INTO pays_enum VALUES ('Turquie');