INSERT INTO equipes_pro_enum VALUES ('FC Bayern');
INSERT INTO equipes_pro_enum VALUES ('Olympique Lyonnais');
INSERT INTO equipes_pro_enum VALUES ('France National');
INSERT INTO equipes_pro_enum VALUES ('Real Madrid');
INSERT INTO equipes_pro_enum VALUES ('Manchester United F.C.');
INSERT INTO equipes_pro_enum VALUES ('Arsenal F.C.');
INSERT INTO equipes_pro_enum VALUES ('Chelsea F.C.');
INSERT INTO equipes_pro_enum VALUES ('Brazil nationnal');
INSERT INTO equipes_pro_enum VALUES ('AS Monaco');
INSERT INTO equipes_pro_enum VALUES ('Liverpool F.C.');
INSERT INTO equipes_pro_enum VALUES ('Spain N.F.C.');
INSERT INTO equipes_pro_enum VALUES ('F.C. Barcelona');


INSERT INTO equipe_foot VALUES ('Uruguay', '1', '7', '12');
INSERT INTO equipe_foot VALUES ('Italie', '1', '17', '26');
INSERT INTO equipe_foot VALUES ('France', '1', '27', '10');
INSERT INTO equipe_foot VALUES ('Canada', '1', '37', '5');
INSERT INTO equipe_foot VALUES ('Bresil', '1', '47', '21');
INSERT INTO equipe_foot VALUES ('Suisse', '1', '57', '30');
INSERT INTO equipe_foot VALUES ('Suede', '1', '67', '16');
INSERT INTO equipe_foot VALUES ('Chili', '1', '77', '14');
INSERT INTO equipe_foot VALUES ('Angleterre', '1', '87', '19');
INSERT INTO equipe_foot VALUES ('Mexique', '1', '97', '20');
INSERT INTO equipe_foot VALUES ('Allemagne', '1', '107', '18');
INSERT INTO equipe_foot VALUES ('Portugal', '1', '117', '11');
INSERT INTO equipe_foot VALUES ('Autriche', '1', '127', '25');
INSERT INTO equipe_foot VALUES ('Yougoslavie', '1', '137', '27');
INSERT INTO equipe_foot VALUES ('Union sovietique', '1', '147', '17');
INSERT INTO equipe_foot VALUES ('Tchecoslovaquie', '1', '157', '7');
INSERT INTO equipe_foot VALUES ('Pologne', '1', '167', '13');
INSERT INTO equipe_foot VALUES ('Argentine', '1', '177', '28');
INSERT INTO equipe_foot VALUES ('Belgique', '1', '187', '23');
INSERT INTO equipe_foot VALUES ('Croatie', '1', '197', '3');
INSERT INTO equipe_foot VALUES ('Pays-Bas', '1', '207', '2');
INSERT INTO equipe_foot VALUES ('Coree du Sud', '1', '217', '29');
INSERT INTO equipe_foot VALUES ('Japon', '1', '227', '8');
INSERT INTO equipe_foot VALUES ('Russie', '1', '237', '24');
INSERT INTO equipe_foot VALUES ('Maroque', '1', '247', '15');
INSERT INTO equipe_foot VALUES ('Egypt', '1', '257', '4');
INSERT INTO equipe_foot VALUES ('Grece', '1', '267', '1');
INSERT INTO equipe_foot VALUES ('Qatar', '1', '277', '9');
INSERT INTO equipe_foot VALUES ('Etats-Unis', '1', '287', '22');
INSERT INTO equipe_foot VALUES ('Turquie', '1', '297', '6');
INSERT INTO equipe_foot VALUES ('Uruguay', '2', '7', '3');
INSERT INTO equipe_foot VALUES ('Italie', '2', '17', '25');
INSERT INTO equipe_foot VALUES ('France', '2', '27', '10');
INSERT INTO equipe_foot VALUES ('Canada', '2', '37', '29');
INSERT INTO equipe_foot VALUES ('Bresil', '2', '47', '21');
INSERT INTO equipe_foot VALUES ('Suisse', '2', '57', '14');
INSERT INTO equipe_foot VALUES ('Suede', '2', '67', '4');
INSERT INTO equipe_foot VALUES ('Chili', '2', '77', '30');
INSERT INTO equipe_foot VALUES ('Angleterre', '2', '87', '5');
INSERT INTO equipe_foot VALUES ('Mexique', '2', '97', '20');
INSERT INTO equipe_foot VALUES ('Allemagne', '2', '107', '28');
INSERT INTO equipe_foot VALUES ('Portugal', '2', '117', '19');
INSERT INTO equipe_foot VALUES ('Autriche', '2', '127', '6');
INSERT INTO equipe_foot VALUES ('Yougoslavie', '2', '137', '27');
INSERT INTO equipe_foot VALUES ('Union sovietique', '2', '147', '11');
INSERT INTO equipe_foot VALUES ('Tchecoslovaquie', '2', '157', '16');
INSERT INTO equipe_foot VALUES ('Pologne', '2', '167', '18');
INSERT INTO equipe_foot VALUES ('Argentine', '2', '177', '24');
INSERT INTO equipe_foot VALUES ('Belgique', '2', '187', '22');
INSERT INTO equipe_foot VALUES ('Croatie', '2', '197', '13');
INSERT INTO equipe_foot VALUES ('Pays-Bas', '2', '207', '15');
INSERT INTO equipe_foot VALUES ('Coree du Sud', '2', '217', '26');
INSERT INTO equipe_foot VALUES ('Japon', '2', '227', '1');
INSERT INTO equipe_foot VALUES ('Russie', '2', '237', '7');
INSERT INTO equipe_foot VALUES ('Maroque', '2', '247', '17');
INSERT INTO equipe_foot VALUES ('Egypt', '2', '257', '23');
INSERT INTO equipe_foot VALUES ('Grece', '2', '267', '12');
INSERT INTO equipe_foot VALUES ('Qatar', '2', '277', '8');
INSERT INTO equipe_foot VALUES ('Etats-Unis', '2', '287', '2');
INSERT INTO equipe_foot VALUES ('Turquie', '2', '297', '9');
INSERT INTO equipe_foot VALUES ('Uruguay', '3', '7', '8');
INSERT INTO equipe_foot VALUES ('Italie', '3', '17', '16');
INSERT INTO equipe_foot VALUES ('France', '3', '27', '9');
INSERT INTO equipe_foot VALUES ('Canada', '3', '37', '13');
INSERT INTO equipe_foot VALUES ('Bresil', '3', '47', '1');
INSERT INTO equipe_foot VALUES ('Suisse', '3', '57', '3');
INSERT INTO equipe_foot VALUES ('Suede', '3', '67', '19');
INSERT INTO equipe_foot VALUES ('Chili', '3', '77', '4');
INSERT INTO equipe_foot VALUES ('Angleterre', '3', '87', '15');
INSERT INTO equipe_foot VALUES ('Mexique', '3', '97', '23');
INSERT INTO equipe_foot VALUES ('Allemagne', '3', '107', '6');
INSERT INTO equipe_foot VALUES ('Portugal', '3', '117', '30');
INSERT INTO equipe_foot VALUES ('Autriche', '3', '127', '27');
INSERT INTO equipe_foot VALUES ('Yougoslavie', '3', '137', '22');
INSERT INTO equipe_foot VALUES ('Union sovietique', '3', '147', '17');
INSERT INTO equipe_foot VALUES ('Tchecoslovaquie', '3', '157', '25');
INSERT INTO equipe_foot VALUES ('Pologne', '3', '167', '5');
INSERT INTO equipe_foot VALUES ('Argentine', '3', '177', '12');
INSERT INTO equipe_foot VALUES ('Belgique', '3', '187', '14');
INSERT INTO equipe_foot VALUES ('Croatie', '3', '197', '24');
INSERT INTO equipe_foot VALUES ('Pays-Bas', '3', '207', '10');
INSERT INTO equipe_foot VALUES ('Coree du Sud', '3', '217', '7');
INSERT INTO equipe_foot VALUES ('Japon', '3', '227', '21');
INSERT INTO equipe_foot VALUES ('Russie', '3', '237', '2');
INSERT INTO equipe_foot VALUES ('Maroque', '3', '247', '28');
INSERT INTO equipe_foot VALUES ('Egypt', '3', '257', '18');
INSERT INTO equipe_foot VALUES ('Grece', '3', '267', '20');
INSERT INTO equipe_foot VALUES ('Qatar', '3', '277', '29');
INSERT INTO equipe_foot VALUES ('Etats-Unis', '3', '287', '26');
INSERT INTO equipe_foot VALUES ('Turquie', '3', '297', '11');
INSERT INTO equipe_foot VALUES ('Uruguay', '4', '7', '9');
INSERT INTO equipe_foot VALUES ('Italie', '4', '17', '4');
INSERT INTO equipe_foot VALUES ('France', '4', '27', '26');
INSERT INTO equipe_foot VALUES ('Canada', '4', '37', '21');
INSERT INTO equipe_foot VALUES ('Bresil', '4', '47', '20');
INSERT INTO equipe_foot VALUES ('Suisse', '4', '57', '13');
INSERT INTO equipe_foot VALUES ('Suede', '4', '67', '6');
INSERT INTO equipe_foot VALUES ('Chili', '4', '77', '23');
INSERT INTO equipe_foot VALUES ('Angleterre', '4', '87', '12');
INSERT INTO equipe_foot VALUES ('Mexique', '4', '97', '25');
INSERT INTO equipe_foot VALUES ('Allemagne', '4', '107', '29');
INSERT INTO equipe_foot VALUES ('Portugal', '4', '117', '27');
INSERT INTO equipe_foot VALUES ('Autriche', '4', '127', '14');
INSERT INTO equipe_foot VALUES ('Yougoslavie', '4', '137', '2');
INSERT INTO equipe_foot VALUES ('Union sovietique', '4', '147', '5');
INSERT INTO equipe_foot VALUES ('Tchecoslovaquie', '4', '157', '17');
INSERT INTO equipe_foot VALUES ('Pologne', '4', '167', '18');
INSERT INTO equipe_foot VALUES ('Argentine', '4', '177', '22');
INSERT INTO equipe_foot VALUES ('Belgique', '4', '187', '8');
INSERT INTO equipe_foot VALUES ('Croatie', '4', '197', '30');
INSERT INTO equipe_foot VALUES ('Pays-Bas', '4', '207', '16');
INSERT INTO equipe_foot VALUES ('Coree du Sud', '4', '217', '19');
INSERT INTO equipe_foot VALUES ('Japon', '4', '227', '24');
INSERT INTO equipe_foot VALUES ('Russie', '4', '237', '1');
INSERT INTO equipe_foot VALUES ('Maroque', '4', '247', '7');
INSERT INTO equipe_foot VALUES ('Egypt', '4', '257', '10');
INSERT INTO equipe_foot VALUES ('Grece', '4', '267', '28');
INSERT INTO equipe_foot VALUES ('Qatar', '4', '277', '15');
INSERT INTO equipe_foot VALUES ('Etats-Unis', '4', '287', '3');
INSERT INTO equipe_foot VALUES ('Turquie', '4', '297', '11');
INSERT INTO equipe_foot VALUES ('Uruguay', '5', '7', '4');
INSERT INTO equipe_foot VALUES ('Italie', '5', '17', '7');
INSERT INTO equipe_foot VALUES ('France', '5', '27', '10');
INSERT INTO equipe_foot VALUES ('Canada', '5', '37', '12');
INSERT INTO equipe_foot VALUES ('Bresil', '5', '47', '14');
INSERT INTO equipe_foot VALUES ('Suisse', '5', '57', '16');
INSERT INTO equipe_foot VALUES ('Suede', '5', '67', '11');
INSERT INTO equipe_foot VALUES ('Chili', '5', '77', '26');
INSERT INTO equipe_foot VALUES ('Angleterre', '5', '87', '18');
INSERT INTO equipe_foot VALUES ('Mexique', '5', '97', '29');
INSERT INTO equipe_foot VALUES ('Allemagne', '5', '107', '28');
INSERT INTO equipe_foot VALUES ('Portugal', '5', '117', '6');
INSERT INTO equipe_foot VALUES ('Autriche', '5', '127', '21');
INSERT INTO equipe_foot VALUES ('Yougoslavie', '5', '137', '22');
INSERT INTO equipe_foot VALUES ('Union sovietique', '5', '147', '23');
INSERT INTO equipe_foot VALUES ('Tchecoslovaquie', '5', '157', '20');
INSERT INTO equipe_foot VALUES ('Pologne', '5', '167', '17');
INSERT INTO equipe_foot VALUES ('Argentine', '5', '177', '25');
INSERT INTO equipe_foot VALUES ('Belgique', '5', '187', '2');
INSERT INTO equipe_foot VALUES ('Croatie', '5', '197', '1');
INSERT INTO equipe_foot VALUES ('Pays-Bas', '5', '207', '5');
INSERT INTO equipe_foot VALUES ('Coree du Sud', '5', '217', '9');
INSERT INTO equipe_foot VALUES ('Japon', '5', '227', '30');
INSERT INTO equipe_foot VALUES ('Russie', '5', '237', '24');
INSERT INTO equipe_foot VALUES ('Maroque', '5', '247', '3');
INSERT INTO equipe_foot VALUES ('Egypt', '5', '257', '13');
INSERT INTO equipe_foot VALUES ('Grece', '5', '267', '27');
INSERT INTO equipe_foot VALUES ('Qatar', '5', '277', '15');
INSERT INTO equipe_foot VALUES ('Etats-Unis', '5', '287', '8');
INSERT INTO equipe_foot VALUES ('Turquie', '5', '297', '19');
INSERT INTO equipe_foot VALUES ('Uruguay', '6', '7', '29');
INSERT INTO equipe_foot VALUES ('Italie', '6', '17', '30');
INSERT INTO equipe_foot VALUES ('France', '6', '27', '25');
INSERT INTO equipe_foot VALUES ('Canada', '6', '37', '6');
INSERT INTO equipe_foot VALUES ('Bresil', '6', '47', '13');
INSERT INTO equipe_foot VALUES ('Suisse', '6', '57', '2');
INSERT INTO equipe_foot VALUES ('Suede', '6', '67', '19');
INSERT INTO equipe_foot VALUES ('Chili', '6', '77', '3');
INSERT INTO equipe_foot VALUES ('Angleterre', '6', '87', '10');
INSERT INTO equipe_foot VALUES ('Mexique', '6', '97', '28');
INSERT INTO equipe_foot VALUES ('Allemagne', '6', '107', '14');
INSERT INTO equipe_foot VALUES ('Portugal', '6', '117', '8');
INSERT INTO equipe_foot VALUES ('Autriche', '6', '127', '21');
INSERT INTO equipe_foot VALUES ('Yougoslavie', '6', '137', '22');
INSERT INTO equipe_foot VALUES ('Union sovietique', '6', '147', '7');
INSERT INTO equipe_foot VALUES ('Tchecoslovaquie', '6', '157', '17');
INSERT INTO equipe_foot VALUES ('Pologne', '6', '167', '16');
INSERT INTO equipe_foot VALUES ('Argentine', '6', '177', '11');
INSERT INTO equipe_foot VALUES ('Belgique', '6', '187', '12');
INSERT INTO equipe_foot VALUES ('Croatie', '6', '197', '23');
INSERT INTO equipe_foot VALUES ('Pays-Bas', '6', '207', '4');
INSERT INTO equipe_foot VALUES ('Coree du Sud', '6', '217', '1');
INSERT INTO equipe_foot VALUES ('Japon', '6', '227', '15');
INSERT INTO equipe_foot VALUES ('Russie', '6', '237', '5');
INSERT INTO equipe_foot VALUES ('Maroque', '6', '247', '26');
INSERT INTO equipe_foot VALUES ('Egypt', '6', '257', '27');
INSERT INTO equipe_foot VALUES ('Grece', '6', '267', '18');
INSERT INTO equipe_foot VALUES ('Qatar', '6', '277', '24');
INSERT INTO equipe_foot VALUES ('Etats-Unis', '6', '287', '9');
INSERT INTO equipe_foot VALUES ('Turquie', '6', '297', '20');