INSERT INTO match_foot VALUES ('1998-06-10', 'Uruguay', 'Allemagne', 'Quart de finale', '1', '0', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'Italie', 'Portugal', 'Ronde de groupe', '6', '5', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'France', 'Autriche', 'Finale', '1', '0', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'Canada', 'Yougoslavie', 'Ronde de groupe', '5', '0', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'Bresil', 'Union sovietique', 'Ronde de groupe', '5', '2', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'Suisse', 'Tchecoslovaquie', 'Ronde de 16', '2', '1', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'Suede', 'Pologne', 'Ronde de 16', '1', '3', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'Chili', 'Argentine', 'Finale', '5', '4', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'Angleterre', 'Belgique', 'Ronde de 16', '5', '0', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('1998-06-10', 'Mexique', 'Croatie', 'Ronde de 16', '4', '2', '1', 'Rocket Center', 'Hillford');
INSERT INTO match_foot VALUES ('2002-05-31', 'Italie', 'Autriche', 'Ronde de 16', '3', '0', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'France', 'Yougoslavie', 'Match de 3e place', '3', '5', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'Canada', 'Union sovietique', 'Match de 3e place', '3', '0', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'Bresil', 'Tchecoslovaquie', 'Finale', '1', '5', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'Suisse', 'Pologne', 'Ronde de groupe', '4', '0', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'Suede', 'Argentine', 'Semi-finale', '0', '3', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'Chili', 'Belgique', 'Ronde de 16', '0', '4', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'Angleterre', 'Croatie', 'Ronde de 16', '0', '4', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'Mexique', 'Pays-Bas', 'Finale', '5', '4', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2002-05-31', 'Allemagne', 'Coree du Sud', 'Finale', '3', '4', '2', 'Bob Center', 'Harmsby');
INSERT INTO match_foot VALUES ('2006-06-09', 'France', 'Union sovietique', 'Quart de finale', '2', '3', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Canada', 'Tchecoslovaquie', 'Finale', '3', '5', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Bresil', 'Pologne', 'Ronde de groupe', '0', '1', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Suisse', 'Argentine', 'Ronde de groupe', '0', '2', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Suede', 'Belgique', 'Match de 3e place', '3', '5', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Chili', 'Croatie', 'Finale', '4', '1', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Angleterre', 'Pays-Bas', 'Semi-finale', '1', '4', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Mexique', 'Coree du Sud', 'Semi-finale', '3', '4', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Allemagne', 'Japon', 'Match de 3e place', '2', '3', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2006-06-09', 'Portugal', 'Russie', 'Ronde de groupe', '1', '0', '3', 'Super Field', 'Croma');
INSERT INTO match_foot VALUES ('2010-06-11', 'Canada', 'Pologne', 'Match de 3e place', '0', '1', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Bresil', 'Argentine', 'Ronde de groupe', '4', '3', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Suisse', 'Belgique', 'Ronde de 16', '2', '0', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Suede', 'Croatie', 'Semi-finale', '5', '2', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Chili', 'Pays-Bas', 'Ronde de 16', '2', '0', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Angleterre', 'Coree du Sud', 'Ronde de 16', '5', '3', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Mexique', 'Japon', 'Ronde de groupe', '1', '0', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Allemagne', 'Russie', 'Ronde de 16', '0', '1', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Portugal', 'Maroque', 'Semi-finale', '0', '3', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2010-06-11', 'Autriche', 'Egypt', 'Finale', '5', '4', '4', 'Fern field', 'Bobski');
INSERT INTO match_foot VALUES ('2014-06-12', 'Bresil', 'Belgique', 'Ronde de groupe', '5', '0', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Suisse', 'Croatie', 'Ronde de 16', '2', '3', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Suede', 'Pays-Bas', 'Quart de finale', '5', '2', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Chili', 'Coree du Sud', 'Finale', '3', '4', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Angleterre', 'Japon', 'Quart de finale', '1', '5', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Mexique', 'Russie', 'Quart de finale', '4', '3', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Allemagne', 'Maroque', 'Ronde de groupe', '1', '2', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Portugal', 'Egypt', 'Semi-finale', '1', '4', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Autriche', 'Grece', 'Semi-finale', '3', '0', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2014-06-12', 'Yougoslavie', 'Qatar', 'Ronde de 16', '2', '3', '5', 'Grandios Stadium', 'Hadderfoo');
INSERT INTO match_foot VALUES ('2018-06-14', 'Suisse', 'Pays-Bas', 'Semi-finale', '0', '1', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Suede', 'Coree du Sud', 'Semi-finale', '0', '1', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Chili', 'Japon', 'Ronde de groupe', '5', '1', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Angleterre', 'Russie', 'Finale', '2', '0', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Mexique', 'Maroque', 'Ronde de groupe', '2', '3', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Allemagne', 'Egypt', 'Quart de finale', '0', '3', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Portugal', 'Grece', 'Semi-finale', '3', '2', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Autriche', 'Qatar', 'Finale', '2', '4', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Yougoslavie', 'Etats-Unis', 'Match de 3e place', '5', '4', '6', 'Cookie Center', 'Sier');
INSERT INTO match_foot VALUES ('2018-06-14', 'Union sovietique', 'Turquie', 'Ronde de 16', '6', '5', '6', 'Cookie Center', 'Sier');