INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('11', '170', 'Uruguay', 'Allemagne', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('13', '170', 'Uruguay', 'Allemagne', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('21', '60', 'Italie', 'Portugal', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('25', '150', 'Italie', 'Portugal', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('24', '160', 'Italie', 'Portugal', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('26', '160', 'Italie', 'Portugal', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('21', '230', 'Italie', 'Portugal', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('23', '230', 'Italie', 'Portugal', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('33', '100', 'France', 'Autriche', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('36', '110', 'France', 'Autriche', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('34', '200', 'France', 'Autriche', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('32', '200', 'France', 'Autriche', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('44', '70', 'Canada', 'Yougoslavie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('44', '160', 'Canada', 'Yougoslavie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('41', '160', 'Canada', 'Yougoslavie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('42', '240', 'Canada', 'Yougoslavie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('42', '240', 'Canada', 'Yougoslavie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('54', '100', 'Bresil', 'Union sovietique', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('63', '90', 'Suisse', 'Tchecoslovaquie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('63', '90', 'Suisse', 'Tchecoslovaquie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('65', '120', 'Suisse', 'Tchecoslovaquie', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('64', '170', 'Suisse', 'Tchecoslovaquie', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('66', '170', 'Suisse', 'Tchecoslovaquie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('66', '220', 'Suisse', 'Tchecoslovaquie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('76', '60', 'Suede', 'Pologne', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('75', '120', 'Suede', 'Pologne', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('75', '120', 'Suede', 'Pologne', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('76', '200', 'Suede', 'Pologne', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('83', '140', 'Chili', 'Argentine', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('85', '140', 'Chili', 'Argentine', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('91', '150', 'Angleterre', 'Belgique', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('95', '170', 'Angleterre', 'Belgique', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('91', '230', 'Angleterre', 'Belgique', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('92', '230', 'Angleterre', 'Belgique', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('102', '100', 'Mexique', 'Croatie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('104', '100', 'Mexique', 'Croatie', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('106', '160', 'Mexique', 'Croatie', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('104', '250', 'Mexique', 'Croatie', '1998-06-10', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('103', '250', 'Mexique', 'Croatie', '1998-06-10', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('11', '130', 'Italie', 'Autriche', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('12', '130', 'Italie', 'Autriche', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('12', '210', 'Italie', 'Autriche', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('24', '80', 'France', 'Yougoslavie', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('22', '80', 'France', 'Yougoslavie', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('26', '110', 'France', 'Yougoslavie', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('24', '170', 'France', 'Yougoslavie', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('21', '170', 'France', 'Yougoslavie', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('23', '230', 'France', 'Yougoslavie', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('23', '230', 'France', 'Yougoslavie', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('36', '70', 'Canada', 'Union sovietique', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('35', '70', 'Canada', 'Union sovietique', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('34', '170', 'Canada', 'Union sovietique', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('35', '170', 'Canada', 'Union sovietique', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('32', '250', 'Canada', 'Union sovietique', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('43', '90', 'Bresil', 'Tchecoslovaquie', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('45', '90', 'Bresil', 'Tchecoslovaquie', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('43', '110', 'Bresil', 'Tchecoslovaquie', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('42', '170', 'Bresil', 'Tchecoslovaquie', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('44', '220', 'Bresil', 'Tchecoslovaquie', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('41', '220', 'Bresil', 'Tchecoslovaquie', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('52', '90', 'Suisse', 'Pologne', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('51', '90', 'Suisse', 'Pologne', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('55', '140', 'Suisse', 'Pologne', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('53', '140', 'Suisse', 'Pologne', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('53', '170', 'Suisse', 'Pologne', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('52', '210', 'Suisse', 'Pologne', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('53', '210', 'Suisse', 'Pologne', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('63', '100', 'Suede', 'Argentine', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('66', '190', 'Suede', 'Argentine', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('64', '190', 'Suede', 'Argentine', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('62', '210', 'Suede', 'Argentine', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('64', '210', 'Suede', 'Argentine', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('76', '60', 'Chili', 'Belgique', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('74', '190', 'Chili', 'Belgique', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('74', '250', 'Chili', 'Belgique', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('85', '130', 'Angleterre', 'Croatie', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('86', '190', 'Angleterre', 'Croatie', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('91', '90', 'Mexique', 'Pays-Bas', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('91', '120', 'Mexique', 'Pays-Bas', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('91', '180', 'Mexique', 'Pays-Bas', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('93', '180', 'Mexique', 'Pays-Bas', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('96', '240', 'Mexique', 'Pays-Bas', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('95', '240', 'Mexique', 'Pays-Bas', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('101', '140', 'Allemagne', 'Coree du Sud', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('105', '200', 'Allemagne', 'Coree du Sud', '2002-05-31', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('103', '240', 'Allemagne', 'Coree du Sud', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('102', '240', 'Allemagne', 'Coree du Sud', '2002-05-31', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('11', '130', 'France', 'Union sovietique', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('16', '130', 'France', 'Union sovietique', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('16', '200', 'France', 'Union sovietique', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('12', '200', 'France', 'Union sovietique', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('13', '230', 'France', 'Union sovietique', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('16', '230', 'France', 'Union sovietique', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('24', '60', 'Canada', 'Tchecoslovaquie', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('22', '110', 'Canada', 'Tchecoslovaquie', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('23', '240', 'Canada', 'Tchecoslovaquie', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('24', '240', 'Canada', 'Tchecoslovaquie', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('31', '80', 'Bresil', 'Pologne', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('36', '120', 'Bresil', 'Pologne', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('31', '120', 'Bresil', 'Pologne', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('36', '160', 'Bresil', 'Pologne', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('42', '70', 'Suisse', 'Argentine', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('42', '70', 'Suisse', 'Argentine', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('45', '140', 'Suisse', 'Argentine', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('42', '190', 'Suisse', 'Argentine', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('46', '190', 'Suisse', 'Argentine', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('41', '210', 'Suisse', 'Argentine', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('51', '80', 'Suede', 'Belgique', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('56', '80', 'Suede', 'Belgique', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('53', '140', 'Suede', 'Belgique', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('51', '230', 'Suede', 'Belgique', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('61', '110', 'Chili', 'Croatie', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('72', '120', 'Angleterre', 'Pays-Bas', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('76', '120', 'Angleterre', 'Pays-Bas', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('74', '170', 'Angleterre', 'Pays-Bas', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('76', '170', 'Angleterre', 'Pays-Bas', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('73', '240', 'Angleterre', 'Pays-Bas', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('83', '130', 'Mexique', 'Coree du Sud', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('86', '200', 'Mexique', 'Coree du Sud', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('85', '240', 'Mexique', 'Coree du Sud', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('93', '90', 'Allemagne', 'Japon', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('95', '130', 'Allemagne', 'Japon', '2006-06-09', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('103', '140', 'Portugal', 'Russie', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('105', '140', 'Portugal', 'Russie', '2006-06-09', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('12', '70', 'Canada', 'Pologne', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('11', '70', 'Canada', 'Pologne', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('11', '180', 'Canada', 'Pologne', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('12', '250', 'Canada', 'Pologne', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('23', '130', 'Bresil', 'Argentine', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('35', '150', 'Suisse', 'Belgique', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('31', '180', 'Suisse', 'Belgique', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('46', '80', 'Suede', 'Croatie', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('46', '140', 'Suede', 'Croatie', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('45', '140', 'Suede', 'Croatie', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('46', '200', 'Suede', 'Croatie', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('43', '230', 'Suede', 'Croatie', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('42', '230', 'Suede', 'Croatie', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('56', '80', 'Chili', 'Pays-Bas', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('66', '70', 'Angleterre', 'Coree du Sud', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('66', '70', 'Angleterre', 'Coree du Sud', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('63', '190', 'Angleterre', 'Coree du Sud', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('62', '230', 'Angleterre', 'Coree du Sud', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('64', '230', 'Angleterre', 'Coree du Sud', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('75', '90', 'Mexique', 'Japon', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('75', '90', 'Mexique', 'Japon', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('82', '80', 'Allemagne', 'Russie', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('83', '190', 'Allemagne', 'Russie', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('84', '190', 'Allemagne', 'Russie', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('81', '250', 'Allemagne', 'Russie', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('84', '250', 'Allemagne', 'Russie', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('94', '130', 'Portugal', 'Maroque', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('95', '130', 'Portugal', 'Maroque', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('104', '70', 'Autriche', 'Egypt', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('101', '170', 'Autriche', 'Egypt', '2010-06-11', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('104', '170', 'Autriche', 'Egypt', '2010-06-11', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('12', '100', 'Bresil', 'Belgique', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('15', '100', 'Bresil', 'Belgique', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('12', '150', 'Bresil', 'Belgique', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('16', '220', 'Bresil', 'Belgique', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('13', '220', 'Bresil', 'Belgique', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('21', '60', 'Suisse', 'Croatie', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('26', '140', 'Suisse', 'Croatie', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('25', '180', 'Suisse', 'Croatie', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('24', '220', 'Suisse', 'Croatie', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('24', '220', 'Suisse', 'Croatie', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('31', '70', 'Suede', 'Pays-Bas', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('34', '70', 'Suede', 'Pays-Bas', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('33', '140', 'Suede', 'Pays-Bas', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('31', '140', 'Suede', 'Pays-Bas', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('34', '210', 'Suede', 'Pays-Bas', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('43', '80', 'Chili', 'Coree du Sud', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('54', '110', 'Angleterre', 'Japon', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('54', '250', 'Angleterre', 'Japon', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('54', '250', 'Angleterre', 'Japon', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('62', '60', 'Mexique', 'Russie', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('71', '90', 'Allemagne', 'Maroque', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('72', '140', 'Allemagne', 'Maroque', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('73', '140', 'Allemagne', 'Maroque', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('75', '160', 'Allemagne', 'Maroque', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('73', '160', 'Allemagne', 'Maroque', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('72', '230', 'Allemagne', 'Maroque', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('84', '80', 'Portugal', 'Egypt', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('93', '140', 'Autriche', 'Grece', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('92', '160', 'Autriche', 'Grece', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('104', '160', 'Yougoslavie', 'Qatar', '2014-06-12', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('106', '160', 'Yougoslavie', 'Qatar', '2014-06-12', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('23', '100', 'Suede', 'Coree du Sud', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('25', '100', 'Suede', 'Coree du Sud', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('24', '250', 'Suede', 'Coree du Sud', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('25', '250', 'Suede', 'Coree du Sud', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('34', '90', 'Chili', 'Japon', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('31', '90', 'Chili', 'Japon', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('35', '110', 'Chili', 'Japon', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('36', '180', 'Chili', 'Japon', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('35', '180', 'Chili', 'Japon', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('46', '220', 'Angleterre', 'Russie', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('51', '230', 'Mexique', 'Maroque', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('52', '230', 'Mexique', 'Maroque', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('64', '120', 'Allemagne', 'Egypt', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('66', '120', 'Allemagne', 'Egypt', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('63', '200', 'Allemagne', 'Egypt', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('64', '200', 'Allemagne', 'Egypt', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('62', '230', 'Allemagne', 'Egypt', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('76', '60', 'Portugal', 'Grece', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('72', '110', 'Portugal', 'Grece', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('71', '180', 'Portugal', 'Grece', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('72', '180', 'Portugal', 'Grece', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('72', '210', 'Portugal', 'Grece', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('86', '100', 'Autriche', 'Qatar', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('85', '130', 'Autriche', 'Qatar', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('81', '130', 'Autriche', 'Qatar', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('84', '180', 'Autriche', 'Qatar', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('82', '180', 'Autriche', 'Qatar', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('85', '210', 'Autriche', 'Qatar', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('83', '210', 'Autriche', 'Qatar', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('94', '70', 'Yougoslavie', 'Etats-Unis', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('94', '70', 'Yougoslavie', 'Etats-Unis', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('93', '110', 'Yougoslavie', 'Etats-Unis', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('95', '110', 'Yougoslavie', 'Etats-Unis', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('96', '210', 'Yougoslavie', 'Etats-Unis', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('93', '210', 'Yougoslavie', 'Etats-Unis', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('105', '90', 'Union sovietique', 'Turquie', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('101', '90', 'Union sovietique', 'Turquie', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('103', '140', 'Union sovietique', 'Turquie', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('105', '180', 'Union sovietique', 'Turquie', '2018-06-14', 'Jaune');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('106', '250', 'Union sovietique', 'Turquie', '2018-06-14', 'Rouge');
INSERT INTO sanction (joueur_id, arbitre_id, nation_equipe_1, nation_equipe_2, match_date, couleur) VALUES ('102', '250', 'Union sovietique', 'Turquie', '2018-06-14', 'Rouge');